name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Specify the branch to build (e.g., dev-run)'
        required: true
        default: 'dev-run'
      image_tag:
        type: string
        description: 'Custom Docker image tag (e.g. dev-run)'
        default: 'latest'
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specified branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Log in to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} registry.cn-beijing.aliyuncs.com
      
      - name: Build Docker image
        run: |
          TAG="${{ github.event.inputs.image_tag }}"        
          docker build --platform linux/amd64 --build-arg LIGHTEN=1 -f Dockerfile.backend -t registry.cn-beijing.aliyuncs.com/flyrun/agenticSeek:$TAG .

      - name: Push Docker image
        run: |
          TAG="${{ github.event.inputs.image_tag }}"           
          docker push registry.cn-beijing.aliyuncs.com/flyrun/ragflow:$TAG
